language: generic
sudo: required
services:
- docker
env:
  matrix:
  - IMAGE=29 TESTS=20
  - IMAGE=29 TESTS=70
  - IMAGE=29 TESTS=13
  - IMAGE=29 TESTS=14
  - IMAGE=29 TESTS=17

before_script:
  - docker pull fedora:$IMAGE
  - |
    sudo modprobe kvm-intel nested=1 || :
    sudo modprobe kvm-amd nested=1 || :
    dmesg | tail || :
  - git pull --depth=100
  - |
    git describe --abbrev=0 --tags || :
    git describe --tags || :

script:
- docker run --privileged -it -v $(pwd)/:/dracut fedora:$IMAGE /dracut/fedora-test.sh $IMAGE-$$ "$TESTS"
