language: generic
sudo: required
services:
- docker
env:
  matrix:
  - IMAGE=latest

before_script:
  - docker pull fedora:$IMAGE
  - |
    sudo modprobe kvm-intel nested=1 || :
    sudo modprobe kvm-amd nested=1 || :
    dmesg | tail || :
  - git pull --depth=100
  - |
    git describe --abbrev=0 --tags || :
    git describe --tags || :

script:
- docker run --privileged -it -v $(pwd)/:/dracut fedora:$IMAGE /dracut/fedora-test.sh $IMAGE-$$ "$TESTS"

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/effa917ca3e0ed5fd00e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

